DRAFT: PLT-8079 - Added functionality to take into account a possible upperSlot when calculating stability
input-output-hk/marconi pull request #229
Opened 2023-11-03 18:18 UTC by willjgould

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense and have useful messages
    - [ ] Important changes are reflected in changelog.d of the affected packages
    - [ ] Relevant tickets are mentioned in commit messages
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Targeting main unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] If relevant, reference the ADR in the PR and reference the PR in the ADR
    - [ ] Reviewer requested

2023-11-08 14:42 UTC, willjgould commented on marconi-chain-index/src/Marconi/ChainIndex/Indexers/MintTokenEvent.hs
> +  lastSyncPoint idx = do
Should this take the `lastSyncPoint`s from both indexers and take the minimum instead?

2023-11-08 18:32 UTC, koslambrou requested changes

2023-11-09 11:05 UTC, willjgould commented on marconi-chain-index/src/Marconi/ChainIndex/Indexers/MintTokenEvent.hs
> +  }
I did consider it, but I didn't think it was necessary. However, I also don't fully know the benefits of using it over how I've done it. I presumed it existed to allow us to do more complex queries between tables, and given my queries are quite simple (we use the same `BlockInfo` result for all `Stability` calculations) I figured it was unnecessary complexity. Is there some other benefit that I've missed?

2023-11-09 16:11 UTC, willjgould commented on marconi-chain-index/src/Marconi/ChainIndex/Indexers/MintTokenEvent.hs
> +  }
I'll move it to a new module as is, as discussed on a call.

Will add a comment stating the possibility of moving to the AggregateQuery.

2023-11-14 11:41 UTC, koslambrou approved these changes
LGTM. Small fixes.

2023-11-14 11:41 UTC, koslambrou commented on marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintTokenEvent.hs
> +            withStabilityAllStable
Small convention. Property tests should start with `prop` such as `propWithStabilityAllStable`.

2023-11-14 11:41 UTC, koslambrou commented on marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintTokenEvent.hs
> +getMintTokenEvents
getMintTokenEvents -> genMintTokenEvents

2023-11-14 11:41 UTC, koslambrou commented on marconi-chain-index/test/Spec/Marconi/ChainIndex/Indexers/MintTokenEvent.hs
> +getInputs :: C.BlockNo -> C.TxBody era -> Gen [MintTokenEvent]
getInputs -> genInputs

2023-11-14 19:40 UTC, merged